# Generated by Django 4.2 on 2026-07-20 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(help_text='Employee ID from EmployeeDashboard table')),
                ('shared_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when document was shared')),
                ('file', models.ForeignKey(blank=True, help_text='File being shared (if sharing a file)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='documents.file')),
                ('folder', models.ForeignKey(blank=True, help_text='Folder being shared (if sharing a folder)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='documents.folder')),
                ('shared_by', models.ForeignKey(blank=True, help_text='Admin who shared the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Document',
                'verbose_name_plural': 'Shared Documents',
                'db_table': 'shared_documents',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='shareddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('folder', 'employee_id'), name='unique_shared_folder_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='shareddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('file__isnull', False)), fields=('file', 'employee_id'), name='unique_shared_file_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='shareddocument',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('file__isnull', True), ('folder__isnull', False)), models.Q(('file__isnull', False), ('folder__isnull', True)), _connector='OR'), name='either_folder_or_file_required'),
        ),
    ]
