# Generated by Django 4.2 on 2026-07-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_shareddocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddocument',
            name='shared_by',
        ),
    ]
