# Generated by Django 6.0.6 on 2026-06-25 10:40

import cv_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('desired_position', models.CharField(max_length=255)),
                ('cv_file', models.FileField(upload_to=cv_management.models.cv_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cv_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
