# Generated by Django 4.2 on 2026-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('desired_position', models.CharField(max_length=255)),
                ('cv_file', models.BinaryField()),
                ('cv_file_name', models.CharField(max_length=255)),
                ('cv_file_type', models.CharField(max_length=100)),
                ('cv_file_size', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cv_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
