# Generated by Django 6.0.6 on 2026-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
