# Generated by Django 4.2 on 2026-07-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'job_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('salary_range', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('requirements', models.CharField(max_length=2000)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_openings', to='cv_management.jobtype')),
            ],
            options={
                'db_table': 'job_openings',
                'ordering': ['-created_at'],
            },
        ),
    ]
