const fallbackApi = import.meta.env.DEV
  ? 'http://localhost:8000'
  : 'https://api.rasantsol.com';

export const BASE_URL = (import.meta.env.VITE_API_URL || fallbackApi).replace(/\/?$/, '/');

export const API_ENDPOINTS = {
    LOGIN: '/api/accounts/login/',
    REFRESH_TOKEN: '/api/accounts/token/refresh/',
    LOGOUT: '/api/accounts/logout/',
    PASSWORD_FORGOT: '/api/accounts/password/forgot/',
    PASSWORD_VERIFY_OTP: '/api/accounts/password/verify-otp/',
    PASSWORD_RESET: '/api/accounts/password/reset/',
    PASSWORD_SETUP: (token) => `/api/accounts/password/setup/${token}/`,
    PASSWORD_SETUP_CONFIRM: (token) => `/api/accounts/password/setup/${token}/confirm/`,
    USER_MODULES: '/api/accounts/get_user_modules/',
    USERS_CHAT_LIST: '/api/employeeDashboard/users/chat-list/',
    CONTACT: '/api/accounts/contact/',
    PARSE_CV: '/api/employee_dashboard/parse_cv/',
    CV_SUBMIT: '/api/employeeDashboard/submit-cv/',
    JOB_OPENINGS: '/api/employeeDashboard/job-openings/',
    GET_EMPLOYEES: '/api/employeeDashboard/get_employees/',
    CV_LIST: '/api/employeeDashboard/submit-cv/',
    JOB_CREATE: '/api/employeeDashboard/job-openings/create/',
    JOB_ADMIN_LIST: '/api/employeeDashboard/job-openings/',
    JOB_PUBLIC_LIST: '/api/employeeDashboard/job-openings/',
    JOB_TYPES: '/api/employeeDashboard/job-types/',
    UPDATE_EMPLOYEE: '/api/employeeDashboard/update_employee/',
    ADD_EMPLOYEE: '/api/employeeDashboard/add_employee/',
    JOB_STATUS: '/api/employeeDashboard/job-status/',
    INCREMENT_POLICIES: '/api/employeeDashboard/salaries/policies/',
    INCREMENT_LOOKUPS:  '/api/employeeDashboard/salaries/lookups/',
    POLICY_ASSIGNMENTS: '/api/employeeDashboard/salaries/assignments/',
    POLICY_ASSIGN: (policyId) => `/api/employeeDashboard/salaries/policies/${policyId}/assign/`,
    FORCE_INCREMENT: '/api/employeeDashboard/salaries/force-increment/',
    INCREMENTS_DUE_TODAY: '/api/employeeDashboard/salaries/increment-due-today/',
    CHECK_INSURANCE_RENEWALS:'api/employeeDashboard/salaries/recalculate-insurance/',
    GET_EMPLOYEE_DETAIL: (pk) => `/api/employeeDashboard/salaries/get_employee_detail/${pk}/`,
    EMPLOYEE_MONTHLY_BONUS: (pk) => `/api/employeeDashboard/salaries/employees/${pk}/bonus/`,
    EMPLOYMENT_STATUSES: '/api/employeeDashboard/employment-statuses/',
    CHANGE_EMPLOYMENT_STATUS: (employeeId) => `/api/employeeDashboard/change_employeement_status/${employeeId}/`,

    PAYROLL_SETTINGS: '/api/employeeDashboard/salaries/payroll-settings/',
    HOLIDAYS: '/api/employeeDashboard/holidays/',
    HOLIDAY_DETAIL: (id) => `/api/employeeDashboard/holidays/${id}/`,

    ATTENDANCE: {
        LIST: '/api/employeeDashboard/attendance/employees/',
        HISTORY: (id) => `/api/employeeDashboard/attendance/employees/${id}/history/`,
        BULK_UPLOAD: '/api/employeeDashboard/attendance/bulk-upload/',
        RECORD_UPDATE: (id) => `/api/employeeDashboard/attendance/${id}/`,
        MY_TODAY: '/api/employeeDashboard/attendance/me/today/',
        MY_CHECK_IN: '/api/employeeDashboard/attendance/me/check-in/',
        MY_CHECK_OUT: '/api/employeeDashboard/attendance/me/check-out/',
        MY_OVERVIEW: '/api/employeeDashboard/attendance/me/overview/',
        MY_HISTORY: '/api/employeeDashboard/attendance/me/history/',
        MY_WORK_FROM_HOME: '/api/employeeDashboard/attendance/me/work-from-home/',
        MY_WORK_UPDATE: '/api/employeeDashboard/attendance/me/work-update/',
        OFFICE_LOCATION: '/api/employeeDashboard/attendance/office-location/',
    },

    LEAVE: {
        MY: '/api/employeeDashboard/leave/me/',
        ADMIN_LIST: '/api/employeeDashboard/leave/',
        DECIDE: (id) => `/api/employeeDashboard/leave/${id}/decide/`,
    },

    DOCUMENTS: {
        FOLDERS: {
            CREATE: '/api/documents/folders/create/',
            ROOT: '/api/documents/folders/root/',
            CONTENTS: (id) => `/api/documents/folders/${id}/contents/`,
            UPDATE: (id) => `/api/documents/folders/${id}/update/`,
            DELETE: (id) => `/api/documents/folders/${id}/delete/`,
            ALL: '/api/documents/folders/all/',


        },
        FILES: {
            UPLOAD: '/api/documents/files/upload/',
            VIEW: (id) => `/api/documents/files/${id}/view/`,
            DELETE: (id) => `/api/documents/files/${id}/delete/`,
            UPDATE: (id) => `/api/documents/files/${id}/update/`,
            ALL: '/api/documents/files/all/',
        },
        ALL: '/api/documents/all/',
        SHARE: '/api/documents/share_document/',
        REMOVE_SHARE: '/api/documents/remove-shared-document/',
        GET_EMPLOYEE_DOCUMENTS: (employeeId) => `/api/documents/get_employee_document/${employeeId}/`,
    },

    INBOX_LIST_CONVERSATIONS: '/api/inbox/conversations/',
    INBOX_CREATE_DIRECT: '/api/inbox/conversations/direct/',
    INBOX_LIST_USERS: '/api/inbox/users/',
    INBOX_CREATE_GROUP: '/api/inbox/conversations/group/',
    INBOX_SEND_MESSAGE: '/api/inbox/messages/send/',
    INBOX_GET_MESSAGES: (conversationId) => `/api/inbox/messages/${conversationId}/`,
    INBOX_MARK_READ: (conversationId) => `/api/inbox/messages/${conversationId}/mark-read/`,
    INBOX_SSE_STREAM: '/api/inbox/sse/stream/',
    INBOX_DELETE_FOR_ME: (messageId) => `/api/inbox/messages/${messageId}/delete-for-me/`,
    INBOX_DELETE_FOR_EVERYONE: (messageId) => `/api/inbox/messages/${messageId}/delete-for-everyone/`,
    INBOX_CLEAR_CHAT: (conversationId) => `/api/inbox/conversations/${conversationId}/clear/`,
    INBOX_UPDATE_GROUP_AVATAR: (conversationId) => `/api/inbox/conversations/${conversationId}/avatar/`,
    INBOX_GET_GROUP_AVATAR: (conversationId) => `/api/inbox/conversations/${conversationId}/avatar/image/`,
    INBOX_LEAVE_GROUP: (conversationId) => `/api/inbox/conversations/${conversationId}/leave/`,
    INBOX_ADD_MEMBERS: (conversationId) => `/api/inbox/conversations/${conversationId}/add-members/`,
    INBOX_GET_ATTACHMENT: (attachmentId) => `/api/inbox/messages/attachments/${attachmentId}/`,
    INQUIRY_STATUSES: '/api/accounts/inquiry-statuses/',
    ACCOUNTS_UPDATE_MY_AVATAR: '/api/accounts/profile/avatar/',
    ACCOUNTS_GET_USER_AVATAR: (userId) => `/api/accounts/users/${userId}/avatar/`,
    PROFILE: '/api/accounts/profile/',
    CHANGE_PASSWORD: '/api/accounts/profile/change-password/',
    EMAIL_SETTINGS: '/api/accounts/email-settings/',
    EMAIL_SETTINGS_TEST: '/api/accounts/email-settings/test/',
    OVERVIEW_STATS: '/api/accounts/overview-stats/',
    NOTIFICATIONS: '/api/accounts/notifications/',
    NOTIFICATIONS_MARK_READ: '/api/accounts/notifications/mark-read/',
    NOTIFICATIONS_CLEAR: '/api/accounts/notifications/clear/',
    WORKLOG_ANALYTICS: '/api/worklogs/analytics/',
    WORKLOG_ANALYTICS_EMPLOYEE: (userId) => `/api/worklogs/analytics/employee/${userId}/`,
    WORKLOG_EXPORT_SETTINGS: '/api/worklogs/analytics/export-settings/',
    WORKLOG_ANALYTICS_EXPORT: '/api/worklogs/analytics/export/',
    CREDENTIALS: {
        GET_ALL: '/api/credentials/get_all_credentials/',
        CREATE: '/api/credentials/create/',
        UPDATE: (id) => `/api/credentials/${id}/update/`,
        DELETE: (id) => `/api/credentials/${id}/delete/`,
        SHARE: '/api/credentials/share_credentials/',
        REMOVE_SHARE: '/api/credentials/remove_share/',
        GET_EMPLOYEE_CREDENTIALS: (employeeId) => `/api/credentials/get_credentials/${employeeId}/`,
    }
};
