# Generated by Django 4.2 on 2026-07-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, editable=False, help_text='Auto-generated employee ID (e.g., RS-0726-01)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name (required)', max_length=255)),
                ('email', models.EmailField(help_text='Email address (required)', max_length=254, unique=True)),
                ('cnic', models.CharField(help_text='CNIC number without dashes (required)', max_length=15, unique=True)),
                ('cnic_scan', models.FileField(help_text='CNIC scan copy (required)', upload_to='employee_docs/cnic/')),
                ('present_address', models.TextField(help_text='Present residential address (required)')),
                ('permanent_address', models.TextField(help_text='Permanent residential address (required)')),
                ('phone_number', models.CharField(help_text='Contact phone number (required)', max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender (required)', max_length=10)),
                ('emergency_name', models.CharField(help_text='Emergency contact name (required)', max_length=255)),
                ('emergency_relation', models.CharField(help_text='Relationship (required)', max_length=100)),
                ('emergency_cnic', models.CharField(help_text='Emergency contact CNIC (required)', max_length=15)),
                ('emergency_cnic_scan', models.FileField(help_text='Emergency contact CNIC scan copy (required)', upload_to='employee_docs/emergency/')),
                ('emergency_phone', models.CharField(help_text='Emergency contact phone number (required)', max_length=15)),
                ('emergency_address', models.TextField(help_text='Emergency contact address (required)')),
                ('matric_certificate', models.FileField(help_text='Matric certificate or marksheet (required)', upload_to='employee_docs/education/matric/')),
                ('fsc_certificate', models.FileField(help_text='FSc/Intermediate certificate or marksheet (required)', upload_to='employee_docs/education/fsc/')),
                ('university_degree', models.FileField(help_text='University degree certificate (required)', upload_to='employee_docs/education/university/')),
                ('other_course', models.FileField(blank=True, help_text='Other course certificates (optional)', null=True, upload_to='employee_docs/education/other/')),
                ('bank_name', models.CharField(help_text='Bank name (required)', max_length=255)),
                ('branch_name', models.CharField(help_text='Branch name (required)', max_length=255)),
                ('branch_code', models.CharField(help_text='Branch code (required)', max_length=50)),
                ('iban_number', models.CharField(help_text='IBAN number (required)', max_length=34)),
                ('account_number', models.CharField(help_text='Bank account number (required)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
