# Generated by Django 4.2 on 2026-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
