# Generated by Django 4.2 on 2026-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_conversation_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
