# Generated by Django 4.2 on 2026-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_conversation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='avatar_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
