# Generated by Django 4.2 on 2026-07-20 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Credential/Label name', max_length=200)),
                ('link', models.URLField(blank=True, help_text='URL/Link for the service', max_length=500, null=True)),
                ('username', models.CharField(help_text='Username', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('password', models.CharField(help_text='Password', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created date/time')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'db_table': 'credential_store',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(help_text='Employee ID from EmployeeDashboard table')),
                ('shared_at', models.DateTimeField(auto_now_add=True, help_text='Date/Time when shared')),
                ('credential', models.ForeignKey(help_text='Reference to the credential being shared', on_delete=django.db.models.deletion.CASCADE, related_name='shared_credentials', to='credentialVault.credentialstore')),
                ('user', models.ForeignKey(help_text='User account of the employee', limit_choices_to={'role_id': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='shared_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Credential',
                'verbose_name_plural': 'Shared Credentials',
                'db_table': 'shared_credentials',
                'ordering': ['-shared_at'],
                'unique_together': {('credential', 'user')},
            },
        ),
    ]
