# Generated by Django 4.2 on 2026-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Credential/Label name', max_length=200)),
                ('link', models.URLField(blank=True, help_text='URL/Link for the service', max_length=500, null=True)),
                ('username', models.CharField(help_text='Username', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('password', models.CharField(help_text='Password', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created date/time')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'db_table': 'credential_store',
                'ordering': ['-created_at'],
            },
        ),
    ]
