# Generated by Django 4.2 on 2026-07-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentialVault', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedcredential',
            unique_together={('credential', 'employee_id')},
        ),
        migrations.RemoveField(
            model_name='sharedcredential',
            name='user',
        ),
    ]
