# Generated by Django 4.2 on 2026-07-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialVault', '0002_alter_sharedcredential_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialstore',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or notes', null=True),
        ),
    ]
