# Generated by Django 4.2 on 2026-07-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentialVault', '0003_credentialstore_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialstore',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='credentialstore',
            name='username',
            field=models.CharField(help_text='Username', max_length=200, unique=True),
        ),
    ]
