# Generated by Django 4.2 on 2026-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
