# Generated by Django 4.2 on 2026-07-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_module_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
