# Generated by Django 4.2 on 2026-07-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar_user_avatar_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
