# Generated by Django 4.2 on 2026-07-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_number',
        ),
    ]
