# Generated by Django 4.2 on 2026-07-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_module_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'inquiry_status',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='accounts.inquirystatus'),
        ),
    ]
