# Generated by Django 3.2.25 on 2026-07-22 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_module_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='mail.rasantsol.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('smtp_username', models.EmailField(default='danialali@rasantsol.com', max_length=254)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('use_tls', models.BooleanField(default=False)),
                ('from_name', models.CharField(default='Rasant Solutions', max_length=120)),
                ('from_email', models.EmailField(default='danialali@rasantsol.com', max_length=254)),
                ('admin_notification_email', models.EmailField(default='danialali@rasantsol.com', help_text='Receives system alerts (increments due, onboarding completed, etc.)', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_increment_digest_sent', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
                'db_table': 'email_settings',
            },
        ),
    ]
