# Generated by Django 4.2 on 2026-07-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_inquirystatus_contactmessage_status'),
        ('accounts', '0012_notification'),
    ]

    operations = [
    ]
