# Generated by Django 4.2 on 2026-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20260724_1534'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_583549_idx',
            old_name='notif_recip_read_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordactiontoken',
            new_name='password_ac_user_id_e6afe3_idx',
            old_name='password_ac_user_purpose_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('inquiry', 'Inquiry'), ('cv', 'CV / Hiring'), ('job', 'Job'), ('increment', 'Increment'), ('status', 'Status'), ('leave', 'Leave'), ('system', 'System')], default='system', max_length=32),
        ),
        migrations.AlterField(
            model_name='passwordactiontoken',
            name='purpose',
            field=models.CharField(choices=[('reset_otp', 'Password reset OTP'), ('reset_session', 'Password reset session'), ('setup', 'Create password (invite)'), ('onboarding', 'Employee onboarding form')], max_length=32),
        ),
    ]
