# Generated by Django 4.2 on 2026-07-12 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeeDashboard', '0003_cvsubmission_job_alter_employee_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'application_mode',
            },
        ),
        migrations.CreateModel(
            name='CycleTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'cycle_timing',
            },
        ),
        migrations.CreateModel(
            name='IncrementPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='employeeDashboard.applicationmode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle_timing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='employeeDashboard.cycletiming')),
            ],
            options={
                'db_table': 'increment_policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncrementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'increment_type',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='increment_applied_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_increment_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryIncrementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_type', models.CharField(max_length=50)),
                ('increment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_history', to='employeeDashboard.employee')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeeDashboard.incrementpolicy')),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
        migrations.AddField(
            model_name='incrementpolicy',
            name='increment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='employeeDashboard.incrementtype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='increment_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employeeDashboard.incrementpolicy'),
        ),
        migrations.CreateModel(
            name='EmployeePolicyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignments', to='employeeDashboard.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='employeeDashboard.incrementpolicy')),
            ],
            options={
                'db_table': 'employee_policy_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('employee', 'policy')},
            },
        ),
    ]
