# Generated by Django 4.2 on 2026-07-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0004_applicationmode_cycletiming_incrementpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_insurance_cycle_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, help_text="Hashed password using Django's PBKDF2 algorithm", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryDeductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_month', models.DateField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_after_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_history', to='employeeDashboard.employee')),
            ],
            options={
                'db_table': 'salary_deduction_history',
                'ordering': ['-deduction_month'],
            },
        ),
    ]
