# Generated by Django 4.2 on 2026-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0004_applicationmode_cycletiming_incrementpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, help_text="Hashed password using Django's PBKDF2 algorithm", max_length=128, null=True),
        ),
    ]
