# Generated by Django 4.2 on 2026-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0005_employee_insurance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_id',
            field=models.IntegerField(blank=True, help_text='Numeric ID used to match bulk attendance CSV uploads to this employee', null=True, unique=True),
        ),
    ]
