# Generated by Django 4.2 on 2026-07-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0005_employee_password'),
    ]

    operations = [

        migrations.CreateModel(
            name='SalaryDeductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_month', models.DateField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_after_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_history', to='employeeDashboard.employee')),
            ],
            options={
                'db_table': 'salary_deduction_history',
                'ordering': ['-deduction_month'],
            },
        ),
    ]
