# Generated by Django 4.2 on 2026-07-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0005_employee_insurance_amount_and_more'),
        ('employeeDashboard', '0006_employee_insurance_amount_and_more'),
    ]

    operations = [
    ]
