# Generated by Django 4.2 on 2026-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0007_timetable_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timetable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
