# Generated by Django 4.2 on 2026-07-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0007_merge_20260720_1236'),
        ('employeeDashboard', '0008_alter_attendance_timetable_delete_timetable'),
    ]

    operations = [
    ]
