# Generated by Django 4.2 on 2026-07-22 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeeDashboard', '0009_merge_20260721_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='attendance_deduction_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='half_day_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='late_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='late_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='late_penalty_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='overtime_rate_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='paid_leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='per_day_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='present_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='total_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='unpaid_absent_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='unpaid_leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_minutes', models.PositiveIntegerField(default=10)),
                ('allowed_leaves_per_month', models.PositiveIntegerField(default=2)),
                ('allowed_absents_per_month', models.PositiveIntegerField(default=0)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('late_count_threshold', models.PositiveIntegerField(default=3, help_text='Free lates per month before half-day penalty starts')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_settings',
            },
        ),
    ]
