# Generated by Django 4.2 on 2026-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0010_attendance_is_paid_attendance_late_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydeductionhistory',
            name='attendance_synced',
            field=models.BooleanField(default=False),
        ),
    ]
