# Generated by Django 4.2 on 2026-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0018_company_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback/reason for employment status changes (especially for resignation)', null=True),
        ),
    ]
