# Generated by Django 4.2 on 2026-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0019_employee_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_amount',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
