# Generated by Django 4.2 on 2026-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0020_alter_employee_current_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
